{application,my_app,
             [{applications,[kernel,stdlib,elixir,logger,postgrex,ecto_sql,
                             mariaex,jason]},
              {description,"my_app"},
              {modules,['Elixir.MyApp','Elixir.MyApp.Application',
                        'Elixir.MyApp.OtherRepo','Elixir.MyApp.Repo']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.MyApp.Application',[]}}]}.
